title: Quantum Modelling Center
description: The Quantum Modelling Center is a open-source platform for hosting software and tutorials themed around the modelling of quantum systems.
email: jdunham@cft.edu.pl

lsi: false
safe: true
source: src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

nav_pages:
  - index.md
  - software.md
  - tutorials.md
  - about.md

collections:
  software:
    output: true
  tutorials:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

sass:
  sass_dir: _sass
  style: :compressed


plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
