title: Quantum Modelling Center
description: The Quantum Modelling Center is a open-source platform for hosting software and tutorials themed around the modelling of quantum systems.
email: jdunham@cft.edu.pl

lsi: false
safe: true
source: src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
baseurl: ""

nav_pages:
  - index.md
  - software.md
  - problems.md
  - tutorials.md
  - about.md

collections:
  software:
    permalink: /:collection/:path/
    output: true
  problems:
    permalink: /:collection/:path/
    output: true
  tutorials:
    permalink: /:collection/:path/
    output: true

breadcrumbs: true  # disabled by default

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: software
    values:
      layout: single
  - scope:
      path: ""
      type: problems
    values:
      layout: single
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      read_time: true
      toc: true
      toc_sticky: true

sass:
  style: :compressed
  load_paths:
    - _sass

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

permalink: /:categories/:year/:month/:day/:title:output_ext
#
# remote_theme: "jekyll/minima@0b7ca6b"
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
