title: Quantum Modelling Centre
email: jdunham@cft.edu.pl

lsi: false
safe: true
source: src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
