title: Quantum Modelling Center
description: The Quantum Modelling Center is a open-source platform for hosting software and tutorials themed around the modelling of quantum systems.
email: jdunham@cft.edu.pl

lsi: false
safe: true
source: src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: "jekyll/minima@0b7ca6b"

nav_pages:
  - index.md
  - software.md
  - tutorials.md
  - about.md

collections:
  software:
    permalink: /:collection/:name
    output: true
  tutorials:
    permalink: /:collection/:name
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

sass:
  style: :compressed
  load_paths:
    - _sass

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

permalink: /:categories/:year/:month/:day/:title:output_ext
