title: Quantum Modelling Center
masthead_title: " "
description: The Quantum Modelling Center is a open-source platform for hosting software and tutorials themed around the modelling of quantum systems.
email: jdunham@cft.edu.pl
repository: CFT-PAN/quantum-modelling-centre

lsi: false
safe: true
source: src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
baseurl: ""

nav_pages:
  - index.md
  - software.md
  - problems.md
  - tutorials.md
  - about.md

collections:
  software:
    permalink: /:collection/:path/
    output: true
  problems:
    permalink: /:collection/:path/
    output: true
  tutorials:
    permalink: /:collection/:path/
    output: true

breadcrumbs: true  # disabled by default

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: software
    values:
      layout: single
      sidebar: true
      show_author: true
  - scope:
      path: ""
      type: problems
    values:
      layout: single
      toc_sidebar: true
      show_author: true
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      read_time: true
      toc_sidebar: true
      show_author: true


logo: assets/images/QMC-LOGO-alpha.png

sass:
  style: :compressed
  load_paths:
    - _sass

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-scholar

permalink: /:categories/:year/:month/:day/:title:output_ext
#
# remote_theme: "jekyll/minima@0b7ca6b"
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

enable_copy_code_button: true

# External urls

links:
  julia: "https://julialang.org"
